### ISSUE TITLE
Missing documention for setting operation id

### ISSUE THREAD

**Issue by janhaviagrawal** [Microsoft/ApplicationInsights-Python#106]
There seems to be no documentation for setting up operation id. It would be really helpful to have some with examples for setting up correlation.
```
tc = TelemetryClient(instrumentation_key=instrumentation_key)
tc.context.operation.id = <operation_id>
tc.track_trace('Test trace')
tc.flush()
```

**Comment by aaronkensci** [comment]
👍 Looking forward to this PR.

**Comment by aaronkensci** [comment]
Ideally some sort of middleware would inject the operation_Id/operation_ParentId's defined in this doc for every telemetry event triggered in a request: https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation

Passing the whole trace context into telemetry events is a good first pass, but ideally users of the AppInsights Python libraries don't need to implement their own operation_Id construction logic.

**Comment by SergeyKanzhelev** [comment]
Part with the missing documentation is committed. Now we have two more improvements - first to have ability to specify `id` per track without creating a new telemetry client. And second - extract and inject identifiers from the headers. For the second one the plan is to migrate to OpenCensus https://github.com/Microsoft/ApplicationInsights-Python/issues/105

I'm closing this issue to avoid confusions
