### ISSUE TITLE
Setting context attributes for logging handler

### ISSUE THREAD

**Issue by janhaviagrawal** [Microsoft/ApplicationInsights-Python#110]
With the latest release, it is possible to set up context.properties for logging handler but it still does not allow setting other context attributes (user, operation etc) passed as channel.context.
This is because in the channel write code
```
local_context = context or self._context
for key, value in self._write_tags(local_context):
    tags[key] = value
```
This ignores the attributes set in the channel itself. This should be
```
for prop_context in [self._context, context]:
    for key, value in self._write_tags(prop_context):
        tags[key] = value
```

**Comment by janhaviagrawal** [comment]
PR for this: https://github.com/Microsoft/ApplicationInsights-Python/pull/114

**Comment by SergeyKanzhelev** [comment]
Thanks again for contribution. As I mentioned in PR - please send CHANGELOG update as well. Closing issue

**Comment by janhaviagrawal** [comment]
PR for CHANGELOG https://github.com/Microsoft/ApplicationInsights-Python/pull/116
