### ISSUE TITLE
WSGIApplication should set operation id from header as defined in App Insights documentation

### ISSUE THREAD

**Issue by aarondwest** [microsoft/ApplicationInsights-Python#115]
The WSGIApplication currently sets the operation id as a random guid: https://github.com/Microsoft/ApplicationInsights-Python/pull/71/files#diff-49597c0d8858a97f87ec4adf464f986dR69

It should be adding the operation id from the headers of the request as defined in the App Insights correlation data model:
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation#correlation-headers

**Comment by SergeyKanzhelev** [comment]
We hope to get it done via the move of this logic to OpenCensus. See https://github.com/Microsoft/ApplicationInsights-Python/issues/105


Basically all auto-collection should be moved there, If you think you can help with this move - it will be great.

**Comment by SergeyKanzhelev** [comment]
I'm closing for now. If you need it right away - I'd accept PR into the current database. Just re-open the issue.

**Comment by aaronkensci** [comment]
I don't want this requirement to be lost in the move to OpenCensus. How can the operation Id/parent operation Id work be tracked as part of the move to OpenCensus?

**Comment by aaronkensci** [comment]
Thank you @SergeyKanzhelev. I don't have the time to add the operation logic to the WSGIApp at the moment, but hopefully I can the future.

For those who are in a similar position, I have added logic to our internal Python telemetry module to inject the 'X-Ms-Request-Id' header into any telemetry events where the Flask context exists. 

It's a mitigation, but we can now correlate our telemetry events across NodeJS and Python services using a query that looks for operationId in the App Insights column and within customDimensions.

```
from Flask import request, has_request_context
def add_correlation_id(self):
        telemetry_dimensions['operation_Id'] = 'Not-Set'
        if has_request_context():
            try:
                if request.headers is not None:
                    if 'X-Ms-Request-Id' in request.headers:
                        # Populate customDimensions with value from header. Doesn't perform the full operationId/parentOperationID data model defined for App Insights.
                        telemetry_dimensions['operation_Id'] = request.headers['X-Ms-Request-Id']
            # Catches error when there is no Flask context
            except AttributeError:
                pass
```
