### ISSUE TITLE
Current approach of exception logging in flask plugin isn's safe

### ISSUE THREAD

**Issue by hirochachacha** [Microsoft/ApplicationInsights-Python#124]
https://github.com/Microsoft/ApplicationInsights-Python/blob/439f175cb446e30d7a541bee03d31393febf88c2/applicationinsights/flask/ext.py#L160-L169

The above code has undesirable side-effects.
It swallow any exceptions - not only critical one, but also [HTTP Exception](http://werkzeug.pocoo.org/docs/0.14/exceptions/#werkzeug.exceptions.HTTPException) which is used for internal control flows such as redirect, 404 hander, ... etc.

You can check it by a following simple program:
```
from flask import Flask

app = Flask(__name__)

@app.errorhandler(Exception)
def handle_exception(e):
    raise e


@app.route('/')
def root():
    return 'hello'


if __name__ == '__main__':
    app.run()
```

Normally, requesting '/notfound' invoke the builtin 404 handler.
In the above code, `@app.errorhandler(Exception)` swallows `werkzeug.exceptions.NotFound`, so the builtin 404 handler is never called.
It means `@app.errorhandler(Exception)` broke a normal flask application.

I'm not sure but I'd suggest using http://flask.pocoo.org/docs/1.0/signals/ instead, which presumably have no side-effects.
I assume that Sentry is doing that approach.

https://github.com/getsentry/raven-python/blob/master/raven/contrib/flask.py#L300-L301

**Comment by c-w** [comment]
Thanks for reporting this issue. The Flask 1.0 release changed the semantics of `@app.errorhandler(Exception)` which is causing the undesired behavior you're seeing.

I've implemented a fix for the error here: https://github.com/Microsoft/ApplicationInsights-Python/pull/158.
