### ISSUE TITLE
Telemetry intermittently missing

### ISSUE THREAD

**Issue by afernando79** [microsoft/ApplicationInsights-Python#127]
Context: We have a data ingest pipeline which uses an eventhub to ETL data from an external source into our Azure MSSQL database. We have been using the telemetry class to log our eventhub consumer and producer events (the extract and transform and load) and have been having intermittent issues where some events are not ending up in our metrics. This is producing false negatives and so requires us to look into querying the end data store, checking the data was ingested.

So far we know the ingest is happening successfully as the data is ending up in SQL, so we have the _better_ case scenario. 

We know we can improve our pipeline and monitoring methods but would like to be able to reply on the metrics produced by the telemetry client. As it stands, the query to check the data is being ingested is expensive (in both time and performance requirements) even with the relevant indexes being created in SQL which is the reason for investing effort in utilising telemetry. Long term we may consider an alternative approach - aggregating the data in cronjobs and loading these data to tables which can be queried instead. But ultimately, we would like to know either way if the telemetry can be relied upon going forward; is there an issue with the library, if there is an issue with our implementation or could there be some configuration tweaks that need to be performed.

The frustration is in its intermittent nature. If anyone has seen anything like this, I'd be most grateful.

**Comment by c-w** [comment]
How are you setting up the AppInsights client? I've seen similar behavior when using the default synchronous sender. Switching to an asynchronous queue and sender makes the telemetry reporting more predictable.

**Comment by michael-chi** [comment]
I am also having similar issue, opend an issue [here](https://github.com/Azure/azure-functions-host/issues/4263), but I guess it's more of Application Insights Python SDK issue ?
