### ISSUE TITLE
Should tc.flush() block?

### ISSUE THREAD

**Issue by snobu** [microsoft/ApplicationInsights-Python#128]
Should `tc.flush()` block or execute on a background thread?

Consider this Flask route:

```python
def predict_image_handler(project=None):
    ...
    results = predict_image(img)

    predictions = {
        'tagName': results['tagName'],
        'confidence': results['probability']
    }

    tc.track_trace('Inference result', predictions)
    tc.flush() # This call blocks
    
    return jsonify(results)
```

If there's a network glitch or a DNS timeout, `tc.flush()` blocks until telemetry is sent (or sending fails, whichever comes first). This means the API response could be delayed past request timeout, which is not cool.

**Comment by mwdavids** [comment]
I have come across this issue as well. My team has a number of lightweight ML services running as flask applications. Using App Insights with a manual flush, which is necessary for any sort of custom logging, increased the response time 10x. When we realized this we converted our services to use the [suggested pattern for flask apps](https://github.com/microsoft/ApplicationInsights-Python#usage), which doesn't block.
