### ISSUE TITLE
Document senders/queues

### ISSUE THREAD

**Issue by gugu91** [microsoft/ApplicationInsights-Python#138]
The behaviour of synchronous and asynchronous sender is not clear without reading the code. Should it be documented? It could also be argued asynchronous might make a better default.

**Comment by gugu91** [comment]
@SergeyKanzhelev let me know your thoughts, happy to contribute

**Comment by SergeyKanzhelev** [comment]
yes, please

**Comment by gugu91** [comment]
I think probably it's not worth documenting until the async sender gets in its final/fixed stage? Linked to issue #139
