### ISSUE TITLE
Setting role_name on Flask app

### ISSUE THREAD

**Issue by vshulev** [Microsoft/ApplicationInsights-Python#146]
I can't find relevant docs on how to set `cloud.role_name` on a Flask app. The `AppInsights` class doesn't seem to have a `context` attribute. Is there a way to set it?

**Comment by c-w** [comment]
The Flask integration currently doesn't provide a way to explicitly set context attributes. You can see this here where the telemetry channel is initialized with the default context: https://github.com/Microsoft/ApplicationInsights-Python/blob/5866580ce8e9761221f5a8be606461d8f23f5e6b/applicationinsights/flask/ext.py#L98 

You could use the following to set the context, but this relies on private attributes so it may not be supported in future versions:

```py
my_context = TelemetryContext()
# ... set attributes on the context

appinsights = AppInsights(app)
appinsights._channel._context = my_context
```

**Comment by c-w** [comment]
I've submitted a pull request for this here: https://github.com/Microsoft/ApplicationInsights-Python/pull/157

If the pull request is merged, you should be able to address your use-case via the following:

```py
appinsights = AppInsights(app)
appinsights.context.cloud.role_name = 'my-role-name'

# all telemetry (e.g. requests, traces, etc.) will include the role name
@app.route('/test')
def test():
    app.logger.info('some message')
    appinsights.flush()
```
