### ISSUE TITLE
cloud_RoleName not being set

### ISSUE THREAD

**Issue by digitaldias** [microsoft/ApplicationInsights-Python#147]
Would you be able to add, or explain how I can add the cloud_RoleName to the Application Insights client?

the closest I've gotten  is a [blog entry by Simon Timms](https://westerndevs.com/app_insights_appname/) who wrote as an example: 

```
appInsightsClient.context.device.role_name = 'EMailSender'
```

However this does not seem to set the **cloud_RoleName** and thus, does not make the application appear on the *Application Map*

Any advice on how to achieve this is appreciated!

**Comment by fonebone42** [comment]
appInsightsClient.context.device.role_name = 'MyRole'

also didn't work for my until I discovered this here:

appInsightsClient.context.cloud.role = 'MyRole'
appInsightsClient.context.cloud.role_instance = 'MyRoleInstance'

now works like a charm

**Comment by pavank** [comment]
I came here by search looking to set this.
