### ISSUE TITLE
Logging isn't sent

### ISSUE THREAD

**Issue by lezi226** [Microsoft/ApplicationInsights-Python#15]
Hi, I tried to using this library to send logging, it never shown in the azure portal. 
But if I invoke LoggingHandler.flush() explicitly, the logging will be shown in portal.

The question is how to make the logging sending to server without explicitly invoking flush()?
From code, looks like there is 1 minute timer in AsynchronousSender.py, but I tried to wait for 1 minute too, still not work.

Thanks

**Comment by lezi226** [comment]
Figured out already. It's SynchronousQueue by default, which only send when local un-sent log count reach 500.
I changed to AsynchronousQueue, then it send every 1 minute.
Thanks

**Comment by bwoods89** [comment]
> Figured out already. It's SynchronousQueue by default, which only send when local un-sent log count reach 500.
> I changed to AsynchronousQueue, then it send every 1 minute.
> Thanks

How did you switch to asynchronous queue?
