### ISSUE TITLE
Open Schema or Data collector API

### ISSUE THREAD

**Issue by tomavitan** [Microsoft/ApplicationInsights-Python#163]
I received an email from Azure with the following title "Migrate from Azure Application Insights Open Schema to the HTTP Data Collector API by April 15, 2019". 

Will it affect our use of this SDK? The email says that "data sent [using Open Schema] to the ingestion endpoint will not be processed."

**Comment by SergeyKanzhelev** [comment]
Open Schema is totally independent feature. Telemetry sent via this SDK will not be affected.
