### ISSUE TITLE
measurements in track_event doesn't accept str value in dict

### ISSUE THREAD

**Issue by Colin-Yu** [microsoft/ApplicationInsights-Python#169]
It looks like that the appinsight in azure portal will not receive my event if I put a str in measurements. Is it expected?

I used applicationinsights==0.11.9. 

My code example 

properties = dict()
        metrics = dict()

        created_time = calc_usage_time(AQUA_SENTINEL_FILE)
        # python appinsights sdk doesn't support str in metrics.
        if created_time:
            metrics['time_usage'] = round((time.time() - created_time) / 60 / 60, 2)
            metrics['start_time'] = datetime.utcfromtimestamp(int(created_time)).astimezone(timezone.utc).strftime("%d-%b-%Y %I:%M:%S %Z")
            metrics['end_time'] = datetime.utcfromtimestamp(int(time.time())).astimezone(timezone.utc).strftime("%d-%b-%Y %I:%M:%S %Z")
        else:
            metrics['time_usage'] = 12.00
            metrics['end_time'] = int(time.time())
            metrics['start_time'] = -1

        tc = TelemetryClient(APPINSIGHTS_KEY)
        telemetry_source = 'CODE'

        properties['correlation-id'] = str(uuid.uuid4())
        properties['service_name'] = telemetry_source
        properties['dependency'] = 'AKS'
        properties['operation_type'] = 'Pod'
        properties['time_unit'] = 'hour'

        tc.track_event(telemetry_source, properties=properties, measurements=metrics)

        tc.flush()

**Comment by jjjordanmsft** [comment]
Yes, measurements are strictly numeric.  Use properties for string data.

Consider using a different telemetry type (remote dependency might be a good one) if you're trying to track time+duration -- as long as that one end of that time range is approximately now.  AFAIK, there's no easy way to change the event time through this SDK.

There are a couple of Kusto functions to help you change other data into datetimes in your queries.  You could (but shouldn't) write datetime strings to properties and parse them with [todatetime](https://docs.microsoft.com/en-us/azure/kusto/query/todatetimefunction) -- but that will result in high cardinality in your properties which isn't great for a couple of reasons.  You could also write unix timestamps to measurements and convert them in your queries with [datetime_add](https://docs.microsoft.com/en-us/azure/kusto/query/datetime-addfunction).

@SergeyKanzhelev might have better ideas or future plans.
