### ISSUE TITLE
Custom event isn't shown in portal

### ISSUE THREAD

**Issue by qin-nz** [Microsoft/ApplicationInsights-Python#17]
Hi, I try to use the library to track event.
I just try following code with my instrumentation key.

```
from applicationinsights import TelemetryClient
tc = TelemetryClient('<YOUR INSTRUMENTATION KEY GOES HERE>')
tc.track_event('Test event')
tc.flush()
```

![image](https://cloud.githubusercontent.com/assets/6998071/17486938/5631822c-5dc5-11e6-9ce8-a7e56fe35546.png)

I won't see anything from azure portal.
![image](https://cloud.githubusercontent.com/assets/6998071/17487082/e5fdbbfa-5dc5-11e6-94c1-35c743c8d94f.png)

I'm not sure whether the data was send to the portal.

**Comment by sudheesh001** [comment]
@qin-nz The events take upto 5 minutes to be reflected on the AppInsights explorer. Can you try using the analytics option and run the query to check if the customEvents have shown up ?

![python customevents](https://cloud.githubusercontent.com/assets/4545925/20656582/7b41fea2-b554-11e6-9eee-a160ca6ed0dd.PNG)

**Comment by qin-nz** [comment]
@sudheesh001 Thanks
