### ISSUE TITLE
Add codeQL to tox build

### ISSUE THREAD

**Issue by lzchen** [microsoft/ApplicationInsights-Python#183]

**Comment by jeremydvoss** [comment]
No longer needed after migrating to azure sdk

**Comment by jeremydvoss** [comment]
CodeQL included: https://github.com/microsoft/ApplicationInsights-Python/blob/a70f8373f7e3eebd96553085f48afd611510b91d/.github/workflows/codeql-analysis.yml#L7

**Comment by jeremydvoss** [comment]
CodeQL included in Azure SDK: https://github.com/Azure/azure-sdk-for-python/blob/604007c97f0971ede180dd40d438c3c9217a1622/eng/pipelines/templates/jobs/ci.yml#L69
