### ISSUE TITLE
Solve Publish action build script permission issue.

### ISSUE THREAD

**Issue by jeremydvoss** [microsoft/ApplicationInsights-Python#204]
Publish action produces following error:
`/home/runner/work/_temp/88c919d4-7306-40d4-90c1-2484c705c158.sh: line 1: ./scripts/build.sh: Permission denied`
https://github.com/microsoft/ApplicationInsights-Python/actions/runs/3131109250

**Comment by lzchen** [comment]
Fixed by https://github.com/microsoft/ApplicationInsights-Python/pull/213
