### ISSUE TITLE
fastapi instrumentation issue with slight change in initialisation

### ISSUE THREAD

**Issue by pkt1583** [microsoft/ApplicationInsights-Python#274]
In https://github.com/microsoft/ApplicationInsights-Python/blob/4fe88bd4cf3449f8c0d162dcac5195399c7b5b23/azure-monitor-opentelemetry/samples/tracing/http_fastapi.py#L22 the fastapi is initialised as fastapi.FastAPI() however if I do slight change in codebase as below the tracing doesn't work as expected

from fastapi import  FastAPI
app = FastAPI()

**Comment by lzchen** [comment]
This is a known limitation of some of the OpenTelemetry instrumentations that create instances of the application. `Flask` is known to have this issue too. Is there an issue in your use case that you can't initialize with `app = fastapi.FastAPI() `?

**Comment by pkt1583** [comment]
I can initialise with fastapi.FastAPI(). if it's known issue then I will close this one
