### ISSUE TITLE
Instrumentation key cannot be none or empty when passing argument to `configure_azure_monitor`

### ISSUE THREAD

**Issue by bastbu** [microsoft/ApplicationInsights-Python#275]
## Description

When executing the [logging sample](https://github.com/microsoft/ApplicationInsights-Python/blob/main/azure-monitor-opentelemetry/samples/logging/simple.py), e.g. the following code (while replacing the connection string with a real connection string):

```python
from logging import WARNING, getLogger

from azure.monitor.opentelemetry import configure_azure_monitor
from opentelemetry.sdk.resources import Resource, ResourceAttributes

configure_azure_monitor(
    connection_string="<redacted>",
    logger_name=__name__,
    logging_level=WARNING,
    resource=Resource.create(
        {
            ResourceAttributes.SERVICE_NAME: "simple_service",
            ResourceAttributes.SERVICE_INSTANCE_ID: "simple_logging_instance",
        }
    ),
    disable_metrics=True,
    disable_tracing=True,
)

logger = getLogger(__name__)

logger.info("info log")
logger.warning("warning log")
logger.error("error log")
```

The following message is printed:

```
> python repro.py 
Failed to parse Instrumentation Key: Instrumentation key cannot be none or empty.
```

The logs still show up in Application Insights.

## Version used

Using `azure-monitor-opentelemetry==1.0.0b11`

**Comment by lzchen** [comment]
It is difficult to diagnose your issue without the connection string value. Could you paste your connection string while omitting sensitive information? (like your ikey)

**Comment by bastbu** [comment]
Sure, here is the updated sample with a connection string of the same form that I used:

```python
from logging import WARNING, getLogger

from azure.monitor.opentelemetry import configure_azure_monitor
from opentelemetry.sdk.resources import Resource, ResourceAttributes

configure_azure_monitor(
    connection_string="InstrumentationKey=ff5577d9-5df2-4798-9912-bf223b5cbe3c;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/",
    logger_name=__name__,
    logging_level=WARNING,
    resource=Resource.create(
        {
            ResourceAttributes.SERVICE_NAME: "simple_service",
            ResourceAttributes.SERVICE_INSTANCE_ID: "simple_logging_instance",
        }
    ),
    disable_metrics=True,
    disable_tracing=True,
)

logger = getLogger(__name__)

logger.info("info log")
logger.warning("warning log")
logger.error("error log")
```

The instrumentation key is substituted with a random GUID.

**Comment by jeremydvoss** [comment]
Hey @bastbu I can't seem to reproduce this issue. 1.0.0b11 appears to work as intended. Can you confirm the following?
 * "InstrumentationKey" is spelled correctly
 * There wasn't a pasteing issue whereby characters were mixed up
 * Whether the script works on different versions of the package?

**Comment by bastbu** [comment]
Thanks for the follow-up, can confirm the following:

- `InstrumentationKey` is spelled correctly, as I'm seeing the message when running the identical sample as above
- When running the identical sample as I pasted, it fails to upload to Application Insights (as the key is not correct), but the warning gets printed
- The script does not print the message on version `1.0.0b10`
- When specifying `APPLICATIONINSIGHTS_CONNECTION_STRING` the warning disappears

> The logs still show up in Application Insights.

To expand on this, as my sentence in the original description was too brief: In both cases (when passing the `connection_string` argument and when using the `APPLICATIONINSIGHTS_CONNECTION_STRING` environment variable) telemetry is correctly exported to Application Insights. When passing the `connection_string` argument the warning appears, even though the behavior is correct (and the exit code of the sample is `0`).

**Comment by jeremydvoss** [comment]
Oh I think I see your issue. You likely have an invalid APPLICATIONINSIGHTS_CONNECTION_STRING configured. The connection string parser will check the env var and notice it is invalid, BUT you still passed in a valid connection string manually. That's why it is still working. TLDR: The message is likely about the APPLICATIONINSIGHTS_CONNECTION_STRING environment variable being misconfigured and does not have to do with the connection string being passed in.

**Comment by bastbu** [comment]
As it only appears to be reproducible in my environment, I'll close the issue.

**Comment by snobu** [comment]
I mean, it does work, just that the error message is misleading:
```
yoguntu:~/monitoring/opentelemetry-python$ python3 sample_flask.py
Failed to parse Instrumentation Key: Instrumentation key cannot be none or empty.
```

May i suggest changing the logic to first try to pass the instrumentation key from whatever it has been given, and if that fails, then fallback to APPLICATIONINSIGHTS_CONNECTION_STRING? If that's missing as well, then throw an error message but be specific that it's now about the env var.
