### ISSUE TITLE
No reaction on the portal, when using this library

### ISSUE THREAD

**Issue by amitbend** [Microsoft/ApplicationInsights-Python#29]
Hi,
I have a flask app on Azure,
I opened a new generic application insights (on a different subscription)

I'm trying to send exceptions with this method
`
import logging
from applicationinsights.logging import enable
`
`
enable(<YOUR INSTRUMENTATION KEY GOES HERE>)
raise Exception('Some exception')
logging.error('This is a message')
`

but i can't see anything on the dashboard

I tried also the other apporach
`from applicationinsights import TelemetryClient
tc = TelemetryClient('<YOUR INSTRUMENTATION KEY GOES HERE>')
try:
    raise Exception('blah')
except:
    tc.track_exception()`

but still nothing.

I don't get any errors on my python script as well.

**Comment by fenchu** [comment]
I have the same issue. How can we add more debugging. No errors whatsoever and no events or metrics in appInsight.

**Comment by dagrooms52** [comment]
I'm also getting no metrics on the App Insights portal. Definitely added my instrumentation key.

**Comment by dagrooms52** [comment]
I was able to find every event that I sent through Application Insights' "Search" feature. For the custom metrics, I had to wait a long time for the event names to be usable in the dashboard. I sent custom metrics to the service at 10:00 this morning and was able to view them at 10:30. You cannot see custom metrics through the search feature. You must create a metric graph and select the name of your metric through the "Custom Metrics" drop-down.

**Comment by mm-manu** [comment]
This is a Flask-related issue.
I figured out a way that works with Flask and uWSGI:

```
app = Flask(__name__)
app.wsgi_app = WSGIApplication(APP_INSIGHTS_KEY, app.wsgi_app) # for request info tracking

@postfork
def worker_setup():
    uwsgi.atexit = worker_deinit
    app.tc = TelemetryClient(APP_INSIGHTS_KEY)

def worker_deinit():
    app.tc.flush()
    print("Goodbye", uwsgi.worker_id())

@app.errorhandler(Exception)
def exception_handler(e):
    app.tc.track_exception(*sys.exc_info(), properties={ 'foo': 'bar' }, measurements={ 'x': 42 })
    app.tc.flush()
    return make_response("Unexpected Exception", 500)
```
Note that this only works when debug is set to False in Flask.
Hope this helps
References: 
https://stackoverflow.com/questions/21627429/flask-and-sys-excepthook
http://flask.pocoo.org/docs/0.12/patterns/errorpages/

**Comment by SergeyKanzhelev** [comment]
Closing as it seems to be addressed
