### ISSUE TITLE
Support for OpenTelemetry instrumentation grpc

### ISSUE THREAD

**Issue by liyakun** [microsoft/ApplicationInsights-Python#299]
Hello, may I ask whether you could add support for grpc instrumentation? Thanks.

[1] https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-grpc

**Comment by jeremydvoss** [comment]
This is not currently a estimated date at which point this will be added as part of the distro. However, you can still trigger the instrumentation yourself after calling configure_azure_monitor. For instance, SQLAlchemy is not a part of the distro, but you can still use it with the distro. See the associated [sample here](https://github.com/microsoft/ApplicationInsights-Python/blob/main/azure-monitor-opentelemetry/samples/tracing/manual.py)

**Comment by jeremydvoss** [comment]
Migrating to Azure sdk: https://github.com/Azure/azure-sdk-for-python/issues/32496
