### ISSUE TITLE
Inbound requests to FastAPI Route are not getting logged in App Insights

### ISSUE THREAD

**Issue by kevinco26** [microsoft/ApplicationInsights-Python#301]
I followed the instructions and the sample project here: https://github.com/microsoft/ApplicationInsights-Python/blob/05a8b1dd3556ab5e7c268c22ee30a365eaf5ec7a/azure-monitor-opentelemetry/samples/tracing/http_fastapi.py#L15. I set up my app insights account and I can see exceptions and dependencies properly getting logged.

However, **the most important one for me, **requests**** is not actually getting populated.. Based on the link above, rqeuests to my FastAPI should automatically be populated. Am I doing something wrong?

Thanks

**Comment by TheUncharted** [comment]
I have the same problem I think

I followed the same example
My context : when deployed I use Azure App Service + Fastapi inside a docker container and in local I just run Fastapi
Those are my libs with poetry : 

opentelemetry-api = "1.17.0"
opentelemetry-sdk = "1.17.0"
azure-monitor-opentelemetry = {version = "^1.0.0b13", allow-prereleases = true}

I tested the tracing and the metrics
For the metrics, it works as expected and for the tracing when I test my routes there is no display of tracing of my routes.

Also I tested also with opentelemetry + azure-monitor-opentelemetry-exporter directly with those libs

azure-monitor-opentelemetry-exporter = {version = "^1.0.0b14", allow-prereleases = true}
opentelemetry-instrumentation-fastapi = "^0.39b0"
opentelemetry-api = "1.18.0"
opentelemetry-sdk = "1.18.0"

and it works

**Comment by kevinco26** [comment]
Hi! I ended up solving this, but I had to just use the opencensus package.. in the end, the problem was how the instrumentation key was being set...

 `app.add_middleware(FastAPIMiddleware, exporter=AzureExporter(connection_string=application_insights_connection_string))`
 `application_insights_connection_string= 'InstrumentationKey=XXXX'`
 
 this in addition to using `from opencensus.ext.azure.trace_exporter import AzureExporter`  did it for me

**Comment by TheUncharted** [comment]
Hey thanks for the tips
what is this FastAPIMiddleware ? is it your custom middleware, if yes can you share it ?
