### ISSUE TITLE
No tracing with Opentelemetry distro for Azure + Python + Fastapi

### ISSUE THREAD

**Issue by TheUncharted** [microsoft/ApplicationInsights-Python#303]
I re-opened this issue from this one [#301](https://github.com/microsoft/ApplicationInsights-Python/issues/301#issue-1780375412
)
Even if there was a workaround , it should work as the sample and be more transparent for the user. 
If not please change and comment the sample

I followed the example at : [FastApi Sample]( https://github.com/microsoft/ApplicationInsights-Python/blob/main/azure-monitor-opentelemetry/samples/tracing/http_fastapi.py)

My context : when deployed I use Azure App Service + Fastapi inside a docker container and in local I just run Fastapi
Those are my libs with poetry :

opentelemetry-api = "1.17.0"
opentelemetry-sdk = "1.17.0"
azure-monitor-opentelemetry = {version = "^1.0.0b13", allow-prereleases = true}

I tested the tracing and the metrics
For the metrics, it works as expected and for the tracing when I test my routes there is no display of tracing of my routes.

Also I tested also with opentelemetry + azure-monitor-opentelemetry-exporter directly with those libs and following some tutos

azure-monitor-opentelemetry-exporter = {version = "^1.0.0b14", allow-prereleases = true}
opentelemetry-instrumentation-fastapi = "^0.39b0"
opentelemetry-api = "1.18.0"
opentelemetry-sdk = "1.18.0"
opentelemetry-instrumentation-fastapi = "^0.39b0"

and it works

This is the pseudo code I put to make it works

```
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from opentelemetry.context import get_current as get_current_context
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider, _Span
from opentelemetry.sdk.trace.export import (BatchSpanProcessor,
                                            ConsoleSpanExporter,
                                            SimpleSpanProcessor)
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from azure.monitor.opentelemetry.exporter import AzureMonitorTraceExporter

tracer = TracerProvider()
tracer.add_span_processor(
    SimpleSpanProcessor(ConsoleSpanExporter())
)
exporter = AzureMonitorTraceExporter.from_connection_string(
    "MY_KEY"
)

tracer.add_span_processor(
    BatchSpanProcessor(exporter)
)

app = FastAPI()
FastAPIInstrumentor.instrument_app(app, tracer_provider=tracer)

@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc):
    span_key = list(get_current_context().keys())[0]
    span = get_current_context().get(span_key)
    assert isinstance(span, _Span)
    return JSONResponse(
        {
            "message": str(exc.detail),
            "trace_id": span.context.trace_id,
            "span_id": span.context.span_id
        },
        status_code=exc.status_code
    )
```

**Comment by lzchen** [comment]
> My context : when deployed I use Azure App Service + Fastapi inside a docker container and in local I just run Fastapi

A bit confused at this sentence. Do you not see any telemetry for an App service fastapi deployed app or no telemetry for a local instance of fast api app?

**Comment by lzchen** [comment]
@TheUncharted  bump. Are you still having issues?
