### ISSUE TITLE
Unwanted dependencies are tracked which are not required

### ISSUE THREAD

**Issue by anandchugh** [microsoft/ApplicationInsights-Python#304]
We are using python opentelemetry sdk to enable tracing and logging in for AzureML pipeline.
After configuring opentelemetry we are seeing lot of dependencies from "management.azure.com", "*.blob.core.widows.net"
These dependencies have almost filled the table.

Is there a way to disable all other dependencies and enable only dependencies which are manually added in code.
``` python
with tracer.start_as_current_spen("abc"):
     test()
```

Also there are some traces added from "*.blob.core.widows.net", which we dont need to track.

**Comment by jeremydvoss** [comment]
The distro by default uses the requests, urllib, and urllib3 instrumentations. Your code may be using these libraries to make dependency network calls. If you are using version 1.0.0b13, you can use the OTEL_PYTHON_DISABLED_INSTRUMENTATIONS to disable those instrumentations while still allowing for manually created spans. See the [README](https://github.com/microsoft/ApplicationInsights-Python/blob/main/azure-monitor-opentelemetry/README.md#usage) for more

**Comment by lzchen** [comment]
@anandchugh 

Is your issue resolved?

**Comment by lzchen** [comment]
Closing issue for now. Feel free to comment if issue persists.
