### ISSUE TITLE
No insights in application map from sample code correlated logs

### ISSUE THREAD

**Issue by TheUncharted** [microsoft/ApplicationInsights-Python#312]
Hello 

I'm testing the the sample of correlated logs [here](https://github.com/microsoft/ApplicationInsights-Python/blob/main/azure-monitor-opentelemetry/samples/logging/correlated_logs.py) 
with a random sleep

When I look in the application map of Application insights I don't see anything, I was expecting to see the  timeline and the span

![image](https://github.com/microsoft/ApplicationInsights-Python/assets/24917492/3f96403d-49f1-4da3-b053-cfeba639570c)

but I can see the traces in logs is it normal ?

![image](https://github.com/microsoft/ApplicationInsights-Python/assets/24917492/281ce8da-3cb5-45bd-b1f3-bec1baf26bb8)

**Comment by lzchen** [comment]
The span is sent to the `dependencies` table as shown below:

![image](https://github.com/microsoft/ApplicationInsights-Python/assets/11580155/ba4348b6-b8c6-481c-8fa4-fa5a28d81467)


The application map is populated by dependency/requests calls. The sample that you ran only creates a single span and has no outbound/inbound calls so the application map does not generate any nodes. Try running the [requests](https://github.com/microsoft/ApplicationInsights-Python/blob/main/azure-monitor-opentelemetry/samples/tracing/http_requests.py) example to get a better understanding of how the app map works.

**Comment by lzchen** [comment]
Closing until further updates.
