### ISSUE TITLE
'MessageData' is required but missing or empty

### ISSUE THREAD

**Issue by TheUncharted** [microsoft/ApplicationInsights-Python#313]
I get this error message

_base.py:_transmit:195 - Data drop 400: 109: Field 'message' on type 'MessageData' is required but missing or empty. Expected: string {'additional_properties': {}, 'version': 1, 'name': 'Microsoft.ApplicationInsights.Message', 'time': '2023-08-30T09:32:28.667781Z', 'sample_rate': 100, 'sequence': None, 'instrumentation_key': '996d131e-5264-4c22-ac88-7edab8d204f0', 'tags': {'ai.device.id': 'MYPC', 'ai.device.locale': 'en_US', 'ai.device.osVersion': '#1 SMP Fri Jan 27 02:56:13 UTC 2023', 'ai.device.type': 'Other', 'ai.internal.sdkVersion': 'py3.9.16:otel1.19.0:ext1.0.0b15', 'ai.cloud.role': 'Test', 'ai.cloud.roleInstance': 'MYPC', 'ai.internal.nodeName': 'MYPC', 'ai.operation.id': '00000000000000000000000000000000', 'ai.operation.parentId': '0000000000000000'}, 'data': <azure.monitor.opentelemetry.exporter._generated.models._models_py3.MonitorBase object at 0x7fe11a034d90>}.

wondering if its related to this bug in java ? [link](https://github.com/microsoft/ApplicationInsights-Java/issues/2393)

**Comment by lzchen** [comment]
@TheUncharted 

Good catch. I am assuming you are using logging with an empty message to generate this exception?

```python
...
logger.warning("")
...
```

**Comment by TheUncharted** [comment]
well I instrumented one of our project with  opentelemetry , and this project use an external library  that log and it seems to generate this error indeed

**Comment by lzchen** [comment]
@TheUncharted 
This issue should be fixed in the latest https://pypi.org/project/azure-monitor-opentelemetry-exporter/1.0.0b17/ release
