### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [Microsoft/ApplicationInsights-Python#32]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [applicationinsights](https://pypi.python.org/pypi/applicationinsights), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install applicationinsights with just the wheel, without having to do any extra work.

**Comment by OsvaldoRosado** [comment]
Interesting. It looks like this repo _should_ already be supporting Wheel from the existance of this file: https://github.com/Microsoft/ApplicationInsights-Python/blob/master/setup.cfg

If my understanding is correct

**Comment by kevin-brown** [comment]
It _should_, yes.

The problem is that the wheels are not being built, so they aren't being sent up to PyPI. I just noticed that this appears to be automatic, [using Travis CI](https://github.com/Microsoft/ApplicationInsights-Python/blob/bb15f9fada7793b6b46b868f2ce112b841f11405/.travis.yml#L8-L15), so only a small change is needed. You just need to [tell Travis to build the wheels](https://docs.travis-ci.com/user/deployment/pypi/#Uploading-different-distributions).
