### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by helger** [Microsoft/ApplicationInsights-Python#36]
The following examples from the README do not see to work:

- Basic logging configuration (first option)
- Basic logging configuration (second option)

There are no errors but no data is being logged on Application Insights.

**Comment by dagrooms52** [comment]
I am having the same problem with this API wrapper.

**Comment by dagrooms52** [comment]
I thought I was also seeing this as well, but the custom events I was sending just took a while to show up in the dashboard.

**Comment by SergeyKanzhelev** [comment]
yes. looks like a time issue
