### ISSUE TITLE
Unexpectedly Exception from SDK

### ISSUE THREAD

**Issue by IanLin419** [microsoft/ApplicationInsights-Python#40]
Hi Expert, 
We encountered App-insights SDK problems in our environments.
We conduct our product on Application Insight service through ApplicationInsights-Python Python SDK.
I discovered three types ERROR from this SDK which we cannot handle.
Could you help me to clarify those message? Thank you.

1.)
app_insights.py:134 - ERROR - sending to app insights https://dc.services.visualstudio.com/v2/track err: <class 'socket.timeout'> The read operation timed out

2.)
app_insights.py:134 - ERROR - sending to app insights https://dc.services.visualstudio.com/v2/track err: <class 'urllib.error.URLError'> <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

3.)
app_insights.py:134 - ERROR - sending to app insights https://dc.services.visualstudio.com/v2/track err: <class 'ConnectionResetError'> [WinError 10054] An existing connection was forcibly closed by the remote host

If you have any concern, please let me know. Thank you.

**Comment by OsvaldoRosado** [comment]
The first and third error look like some kind of network issue. The second is a known issue (https://github.com/Microsoft/ApplicationInsights-node.js/issues/180) that should be ignored and sending the telemetry should be attempted again (I don't know if this SDK is able to do that automatically).

**Comment by IanLin419** [comment]
Hi OsvaldoRosado,
Thanks for your reply.
I've got an information that some known SSL issues in older version of Python2.7.8 particularly.
Is this also a known issue in Python3.5.2?

**Comment by OsvaldoRosado** [comment]
For this particular SSL issue (your second example), this isn't related to the version of Python at all, but is rather a transient server error.

**Comment by IanLin419** [comment]
I see.. so, it's occurring on 3.5.2 as well...
Are the others ERROR(first and third) correlated with SSL issue?
Thanks again!!!

**Comment by OsvaldoRosado** [comment]
From the error names, I don't think they're related errors. They look more like connectivity issues.
