### ISSUE TITLE
process_template_response must return an HttpResponse.

### ISSUE THREAD

**Issue by allieus** [Microsoft/ApplicationInsights-Python#46]
function "process_template_response" must return an HttpResponse. The code below returns None.

Error Point : https://github.com/Microsoft/ApplicationInsights-Python/blob/master/applicationinsights/django/middleware.py#L215

Ref django code : https://github.com/django/django/blob/master/django/core/handlers/base.py#L150

Here's what you can change:

```python
def process_template_response(self, request, response):
    if hasattr(request, 'appinsights') and hasattr(response, 'template_name'):
        data = request.appinsights.request
        data.properties['template_name'] = response.template_name

    return response  # FIX POINT
```

Thanks.

**Comment by jjjordanmsft** [comment]
No, thank *you* for the heads up.

**Comment by jjjordanmsft** [comment]
The fix is merged.  We'll try to get an update out with it soon.

**Comment by Song2017** [comment]
Error:
```
ApplicationInsightsMiddleware.process_template_response didn't return an HttpResponse object. 
It returned None instead.
```
It seems to be same here.

**Comment by Song2017** [comment]
Error:
```
ApplicationInsightsMiddleware.process_template_response didn't return an HttpResponse object. 
It returned None instead.
```
It seems to be same here.
[site with error](https://rgbsdjangodocker.azurewebsites.net/3/results/)

**Comment by Song2017** [comment]
It solved by wheeling [branch  fix46](https://github.com/jjjordanmsft/ApplicationInsights-Python/tree/jjjordan/fix46), here is [applicationinsights-0.10.0-py2.py3-none-any.whl](https://github.com/Song2017/Temp/blob/master/file/applicationinsights-0.10.0-py2.py3-none-any.whl).

Just, Django version with 1.11.4 need use **MIDDLEWARE_CLASSES **

**Comment by jjjordanmsft** [comment]
I've finally pushed 0.11.1 to pypi, which contains this fix.  Very sorry for the delay!
