### ISSUE TITLE
ApplicationInsightsMiddleware.process_template_response didn't return an HttpResponse object.

### ISSUE THREAD

**Issue by dopic** [Microsoft/ApplicationInsights-Python#51]
Hi, 

When my response has a render() method (Django's TemplateResponse), it throws the following exception:

**ApplicationInsightsMiddleware.process_template_response didn't return an HttpResponse object. It returned None instead.**

If I return the response object in method process_template_response from django's middleware, it works fine.

Thanks

**Comment by jjjordanmsft** [comment]
This is a dupe of #46.  There's a wheel at that bug report until we can put out a version that fixes this.  Sorry for the delay.

**Comment by dopic** [comment]
Ok! I'll close this one.
Thanks!

**Comment by jjjordanmsft** [comment]
Jumped the gun on offering a workaround.  I've just pushed 0.11.1 to pypi which has this fix.
