### ISSUE TITLE
Support synchronous mode for Django batch processing

### ISSUE THREAD

**Issue by stakemura** [microsoft/ApplicationInsights-Python#57]
Add support synchronous mode for batch processing [1] in the Django Middleware.
Right now, django command can't push logs when the subsequent processing time is smaller than send_interval.

[1] [Writing custom django-admin commands](https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/#management-commands-and-locales)

**Comment by jjjordanmsft** [comment]
An imperfect workaround might be to set an [atexit](https://docs.python.org/3.6/library/atexit.html) hook to flush the queue and sleep briefly -- there is currently no ways to determine when the data in the queue has been sent.  This might be one good addition.

I'm unsure of whether there's a way to detect whether django is running an admin command and flip to using a SynchronousSender -- at least I wasn't able to find it in the docs.  If there's a way to do that, then there is likely a way to detect it in Settings.  In that case we could to add a flag there.
