### ISSUE TITLE
Exception thrown when Django auth middleware is not used

### ISSUE THREAD

**Issue by deamontg** [Microsoft/ApplicationInsights-Python#59]
**Scenario**
I am writing several Django based APIs that utilize Application Insights for logging. These APIs do not have Django's built-in authentication, so the authentication middleware is not used.

**The problem**
This package does not take this into account, so an exception is thrown when processing the request because `request.user` is not set.

**Solution**
I made the necessary code change to allow for this behavior. Here is the pull request: #58

**Comment by jjjordanmsft** [comment]
Thanks for the fix, I've merged your PR.

**Comment by jjjordanmsft** [comment]
[0.11.2](https://pypi.python.org/pypi/applicationinsights/0.11.2) released.
