### ISSUE TITLE
TelemetryClient (and likely others) never stop trying to send

### ISSUE THREAD

**Issue by glenjamin** [microsoft/ApplicationInsights-Python#60]
I've been investigating https://github.com/Azure/azure-cli/issues/4649

The summary is that our outgoing internet proxy is blocking telemetry requests, and this is causing the upload processes to hang around in an infinite loop every time the `az` CLI is executed.

I've traced this problem down to https://github.com/Microsoft/ApplicationInsights-Python/blob/master/applicationinsights/channel/SenderBase.py#L123-L146

Any time a request fails, it is re-queued for another attempt. There is no code which ever causes this to give up, which is especially problematic when a request will never succeed.

Any thoughts on how this could/should be resolved?
Perhaps a counter should be put on the queue items that can give up after a certain number of failures?
This looks like it could be tricky to implement, as I can't see an envelope on the queue item where this metadata could live.

**Comment by jjjordanmsft** [comment]
That is problematic.  What I don't follow is why this would cause an infinite loop.  Is this somehow blocking the CLI from exiting?  (How?)  That might yield another avenue to address the problem.

And you're right that the fix is not straightforward.  Back-off after failure may help, and a maximum queue size could address memory issues.  Requeueing items after failure is pretty standard across the SDKs.

**Comment by glenjamin** [comment]
The CLI spins off a subprocess to do the upload, it’s the sub process which continuously re-queues, never succeeds and never completes.

**Comment by OsvaldoRosado** [comment]
I think we solve this infinite queuing problem in other SDKs by reading the timestamp off of the payload before sending it. If the telemetry on the disk is too old, it is deleted instead of sent. This is an important optimization regardless as our ingestion won't accept old items.

**Comment by troydai** [comment]
Thanks for fire this issue. On CLI side, I'm going to add a timeout for the spin-off telemetry process to terminate itself. But it would be appropriate to address this issue in ApplicationInsights' SDK.
