### ISSUE TITLE
Error processing response in Django middleware when another request middleware short-circuits

### ISSUE THREAD

**Issue by twschiller** [Microsoft/ApplicationInsights-Python#61]
The Django insights middleware crashes in `process_response` when a middleware short-circuits when processing the request because the `process_request` hasn't be run.

For example, the `CommonMiddleware` will short-circuit to affix a missing trailing slash with a 301 Moved Permanently response if the client accesses `/admin` when `/admin/` is the registered URL

```
MIDDLEWARE_CLASSES = [
    # ...
   'django.middleware.common.CommonMiddleware',
    # ...
   'applicationinsights.django.ApplicationInsightsMiddleware'
]
```

The reasonable solution is probably to check for the presence of the `appinsights` attribute in the `process_response` method. The method can submit the event without the `duration` field set, if the `appinsights` attribute is missing.

**Comment by jjjordanmsft** [comment]
I think in this case, we shouldn't try to process requests/responses if an upstream middleware catches it.  This shouldn't get hit post-Django 1.10, but I hadn't considered that earlier versions called process_response if process_request hadn't first been called (can you confirm?).  If that's the case it looks like the fix you made to your branch would be an acceptable fix to this.

**Comment by cboothe** [comment]
@jjjordanmsft Is there any reason this pull request can be merged into Master?

I am getting the same error.

2018-02-26 19:47:10,145  [django.request:135]  ERROR - Internal Server Error: ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.6/site-packages/applicationinsights/django/middleware.py", line 139, in process_response
    addon = request.appinsights
AttributeError: 'WSGIRequest' object has no attribute 'appinsights'

**Comment by edevil** [comment]
Any news on this?

**Comment by jjjordanmsft** [comment]
I'll get another release out tomorrow with this + #63.

**Comment by jjjordanmsft** [comment]
[0.11.2](https://pypi.python.org/pypi/applicationinsights/0.11.2) released.
