### ISSUE TITLE
Exceptions aren't tracked under "Server exceptions" metric

### ISSUE THREAD

**Issue by twschiller** [microsoft/ApplicationInsights-Python#64]
Application Insights defaults the device type to "Bot" since the library does not provide a value. For servers, the value should be "PC".

We're still working on trying to get the events recognized as server events.

References:
[1] Schema https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Schema/PublicSchema/ContextTagKeys.bond
[2] Device configuration for the official windows server library: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/master/Src/WindowsServer/WindowsServer.Shared/Implementation/DeviceContextReader.cs

**Comment by OsvaldoRosado** [comment]
Can this be worked around with a config change? Eg.:
```
from applicationinsights import TelemetryClient
tc = TelemetryClient('<YOUR INSTRUMENTATION KEY GOES HERE>')
tc.context.device.type = 'PC'
```

**Comment by twschiller** [comment]
It looks like setting the User Agent to be blank in the telemetry requests solves the problem

**Comment by nmhub** [comment]
> It looks like setting the User Agent to be blank in the telemetry requests solves the problem

Hi Todd, could you share some details on how to do that? I couldn't figure out how to see the User Agent on the TelemetryClient. Thanks

**Comment by twschiller** [comment]
@nmhub check out this commit: https://github.com/twschiller/ApplicationInsights-Python/commit/a089700e662bf39af8e46cf3248db0649a934d1a

**Comment by bloodybeet** [comment]
Having the same issue, still unresolved. Have others find a better way than forking the whole codebase and building themselves? :)
