### ISSUE TITLE
Add support for dependency tracking

### ISSUE THREAD

**Issue by twschiller** [Microsoft/ApplicationInsights-Python#66]
To help diagnose server performance issues, it's be great to add support for Application Insight's dependency tracking feature

General:
* Fix contract for Remote Dependency Data
* Add track dependency method to the telemetry client
 
Django Middleware:
* Set the parent ID for the request being processed (see #55) 
* Expose the request ID somehow so that clients can set the parent ID appropriately when calling track dependency. One way to do this is to just expose a telemetry client using thread local storage with the parent ID set to the request ID. (However, I don't think using TLS is recommended by the Django team.)

These changes are all prototyped here: https://github.com/twschiller/ApplicationInsights-Python/commit/fdff3d8fca64597fd2b3e408ed8a2af77d66ce02. 

For those wondering how to track their SQL/cache dependencies when using Django:
* SQL: wrap the `CursorWrapper.execute` and `CursorWrapper.executemany` methods
* Redis (using `django_redis`): wrap the `RedisCache.get` method, which includes both the network call and the deserialization

**Comment by jjjordanmsft** [comment]
This is excellent.  I'll try to dive through this in more depth over the next week (as my schedule allows, sorry :-) )

**Comment by piizei** [comment]
I would expect it to work with WSGIApplication as well.

Ps. 
Here spec how it was in AI java SDK if that is any help:
https://github.com/Microsoft/ApplicationInsights-Java/blob/75f6b6ebbdc96209c085980e34df94d316f8015f/web/src/test/java/com/microsoft/applicationinsights/web/internal/correlation/TelemetryCorrelationUtilsTests.java

**Comment by jjjordanmsft** [comment]
Could you rebase this against the latest in the `develop` branch and open a PR so we can review it?  I think that's the best approach.  Even if it's not finished yet, we can get it in and then start looking at what to improve.  (This will also get us over the CLA requirements).

**Comment by SergeyKanzhelev** [comment]
I'm closing this in favor of https://github.com/Microsoft/ApplicationInsights-Python/issues/105 We will be addressing all distributed tracing scenarios as part of Open Census project
