### ISSUE TITLE
Create contributing.md

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Python#84]
- [x] how to build/test
- [x] should we keep VS project files or switch to VS Code completely?
- [x] how to update documentation (https://github.com/Microsoft/ApplicationInsights-Python/tree/master/doc)

**Comment by aaronkensci** [comment]
Hi, I'd like to contribute a PR but there is no contribution guide. Please share the documentation.

**Comment by SergeyKanzhelev** [comment]
@aaronkensci great! I'm happy you consider helping. I'll put something together hopefully this week.

For now you can simply follow travis file for quick start.

```
python setup.py sdist
python setup.py test
django_tests/all_tests.sh
```

Use `pip install -e <path>` to install it into test application for the testing purposes.

Please ask questions so I can put answers into the contributing file.

And we will probably get rid of proj files in favor of VSCode.

**Comment by aaronkensci** [comment]
@SergeyKanzhelev I have made the code changes, tested it in our service deployment, and run the travis script you have pointed out. All successful.

Please let me know if there are any other steps needed for this PR to be merged.
https://github.com/Microsoft/ApplicationInsights-Python/pull/88/files
