### ISSUE TITLE
Passing custom properties with logging events

### ISSUE THREAD

**Issue by kaa** [microsoft/ApplicationInsights-Python#87]
Version: 0.11.3

Is it possible to pass custom data to Application Insights along with logging events? It seems like the parameters that get passed are fixed at the moment?

https://github.com/Microsoft/ApplicationInsights-Python/blob/adb53ac988f10ca72a0656df5021d01f10e1afbd/applicationinsights/logging/LoggingHandler.py#L94-L100

I'd be interested to get this functionality added and can try to submit a pull request if it is not already possible somehow.

**Comment by SergeyKanzhelev** [comment]
Which instruction have you followed to enable logging? "Basic logging configuration (first option)" from [Readme](https://github.com/Microsoft/ApplicationInsights-Python/blob/master/README.md)?

Do you want to add some constant property to all log messages or something specific for every message? Generally there are two patterns we are following in other languages - telemetry pipeline extensibility when we call telemetry processor for every event just before submitting it into the channel. Or callback on serializing of specific log message from logger infrastructure into Application Insights format. I can give corresponding links. 

Depending on scenario you are trying to enable - recommendations on what feature to implement would be different.

**Comment by kaa** [comment]
Thanks for the super-quick reply. I agree I wasn't quite clear in what I am trying to accomplish.

I'm following the "Basic logging configuration (first option)" approach from the readme, but I think the question is relevant regardless.

Essentially I have two goals, the first one is to pass custom properties with specific calls to the logging methods. Something like the following,

```python
logger = logging.getLogger('jobs')
logger.info('Job completed with status %s', "success", extra={"job_id": "123456"})
```

and here have `job_id` being sent to AI as "Custom Data" which I could use to find all log events related to that `job_id` without having it included in the log message for each row.

The second goal would be to do some sort of scoping like,

```python
logger = logging.getLogger("jobs")
logger.info("start processing jobs")
job_logger = scope_logger(logger, {"job_id":"123456"})
job_logger("starting job") # here {"job_id":"123456"} would be passed automatically
...
```

I suppose I could do that quite easily using a `LoggerAdapter` to add my context to each call, but is there a better way? Python is not really my native language, I'm coming from a dotnet background, so I was thinking there might be a more pythonic way.

**Comment by saschwarz** [comment]
I think I have a similar request/question: I'd like to know how/be able to specify the cloud role (name) in all telemetry data:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-multi-role-apps#use-cloudrolename-to-separate-components

I believe in this scenario the data would ideally be specified once at server start and read from env var/data vault/config file.

**Comment by jjjordanmsft** [comment]
@kaa I'd suggest you have a look at both the [basic logging tutorial](https://docs.python.org/2/howto/logging.html) and [logging cookbook](https://docs.python.org/2/howto/logging-cookbook.html) for more info on Python logging.  It's a fairly big system with a lot of parts.

On your first point - no, we do not currently read in [extra properties from LogRecords](https://docs.python.org/2/library/logging.html#logging.debug) - and perhaps we should read in custom properties as ... custom properties on the telemetry.

As far as sub-loggers, what you are looking for is a [LoggerAdapter](https://docs.python.org/2/howto/logging-cookbook.html#context-info) - that link is from the cookbook and goes into detail on the subject.

**Comment by szklany** [comment]
Hi,

are there any plans on added the the loggers extra content as custom properties?
