### ISSUE TITLE
Flask Integration Not Working

### ISSUE THREAD

**Issue by adamcunnington** [Microsoft/ApplicationInsights-Python#90]
My understanding is that the following is all that is required to cause requests, traces (exceptions) and custom events (logs) to be sent to Application Insights:
applicationinsights.flask.ext.AppInsights(flask.Flask("foo"))

I'm not completely clear on whether I need to be manually calling .flush() or not - please advise.

Either way, I've tried:
app = flask.Flask("foo")
app_insights = applicationinsights.flask.ext.AppInsights(app)
app.logger.info("test")
app_insights.flush()

Requests are logged but no custom events appear in app insights. No errors.

**Comment by SergeyKanzhelev** [comment]
1. Custom events are for usage scenarios primarily. Checkout happened. Configuration was applied. Typically the name of custom event is a low cardinality value you can represent as `enum`. https://docs.microsoft.com/azure/application-insights/application-insights-data-model-event-telemetry

2. Yes, events upload takes a while. It is a known feedback. You do not need to call `flush()` - channel should handle buffers and timers

Closing the issue - please re-open if I haven't answered something
