### ISSUE TITLE
Causes error when used with django.contrib.syndication.views

### ISSUE THREAD

**Issue by jossingram** [Microsoft/ApplicationInsights-Python#95]
I have an RSS feed in my Django app that uses 'django.contrib.syndication.views import Feed' but when Application Insights is running in the app I get this error when visiting the feed url. Django version is 1.11.13, Python 2.7.12

If I remove the middleware line for insights the feed works again.

```
Request Method: | GET
-- | --
http://localhost:8000/latest/news/
1.11.13
AttributeError
'LatestNewsFeed' object has no attribute '__name__'
/usr/local/lib/python2.7/dist-packages/applicationinsights/django/middleware.py in process_view, line 175
/usr/bin/python
2.7.12
['/code',  '/usr/local/bin',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']

```

**Comment by jjjordanmsft** [comment]
Note to others: this only applies if you're using the `use_view_name` setting in config.py, which is not the default.

Hm, this was indeed an oversight.  (What do you mean views aren't always functions?  What's this about old-style classes?)  I'll try to address it shortly.

**Comment by jossingram** [comment]
"What do you mean views aren't always functions?" Not sure what that's referring too, did I say that?

Are you sure you've left the correct comment on the right issue? :(\

If it helps here is the code where the error occurs 

from django.contrib.syndication.views import Feed
from django.urls import reverse
from myapp.models import NewsPage,EventPage,Tag
from datetime import datetime, time

class LatestNewsFeed(Feed):
    title = "Latest news"
    link = "/news/"
    description = "Latest News"
    
    def get_object(self, request):
        return request

    def items(self,request):
        news_root = request.site.root_page
        return NewsPage.objects.descendant_of(news_root).live().order_by('-date')[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.search_description

    def item_pubdate(self, item):
        return datetime.combine(item.date, time())

    def item_link(self, item):
        return item.url

**Comment by jossingram** [comment]
Ah ok, so setting use_view_name to False get's around this.

**Comment by jjjordanmsft** [comment]
Sorry for the cryptic comments.  The issue is that with the syndication framework, your views will be object instances and not functions.  In particular with Python2, it will be an old-style class due to the way it's written, but I've since realized that's not very relevant.

I had written the `use_view_name` code (naively) assuming that every view would be a function.  But object instances don't have the `__name__` property unless you go through `__class__` first -- oops.

And yes, you should be able to work around this for now by turning off that option.

HTH

**Comment by jossingram** [comment]
Ah, I think i get it now! Thanks for the clarification!
