### ISSUE TITLE
role_name and role_instance not uploaded anymore

### ISSUE THREAD

**Issue by timotheeguerin** [Microsoft/ApplicationInsights-Python#96]
Since version 0.11.4(Just tried reverting to 0.11.3 and it works) it seems like `role_name` and `role_instance` are not being passed anymore.

This is I have in the code
```
context = self.telemetry_client.context
context.device.role_name = pool_id
context.device.role_instance = node_id
```
This is the result
![image](https://user-images.githubusercontent.com/1031227/41435019-5d90cb10-6fd2-11e8-8259-e6aaaae1550d.png)

**Comment by SergeyKanzhelev** [comment]
Sorry, I updated schema and didn't mentioned in change log specific changes. Please use `context.cloud.role_name` instead

**Comment by timotheeguerin** [comment]
I see thanks, will give it a try
