### ISSUE TITLE
Provide a package and update documentation for Anaconda

### ISSUE THREAD

**Issue by stansw** [Microsoft/ApplicationInsights-Python#97]
I would like to install all of my dependencies through conda. 

```
(base) >conda install applicationinsights
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - applicationinsights

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Currently the only conda package I found was this one, but it wasn't published by Microsoft.
https://anaconda.org/clinicalgraphics/applicationinsights/files

**Comment by SergeyKanzhelev** [comment]
can you explain why to use `conda`, not `pip`?

**Comment by stansw** [comment]
Deployment script we use in our product makes use of conda. I noticed that other packages published by Microsoft (e.g. azure-storage) are already available for conda. I would like to add just a dependency rather than update the script to combine conda and pip packages.

**Comment by SergeyKanzhelev** [comment]
I don't see Microsoft's azure storage package: https://anaconda.org/search?q=azure-storage Which one are you referring to? I'll also ask internally whether we publish there...

**Comment by stansw** [comment]
This is the one I added to the deployment script previously. 
https://anaconda.org/conda-forge/azure-storage

This issue is more of a question whether ApplicationInsights should publish packages to both places. Was that a miss or intentional decision and I should use pip.

**Comment by SergeyKanzhelev** [comment]
is `conda-forge` some centralized account in anaconda? It doesn't look like something shipped by Microsoft. Do you know how one can ship on behalf of that org?

**Comment by stansw** [comment]
Apparently, the recommended way of installing Microsoft Azure SDK for Python is to use pip. If that's the case then it looks like there is no need for conda support and I just have to update my script.

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python
https://github.com/Azure/azure-sdk-for-python

**Comment by SergeyKanzhelev** [comment]
Thank you for bringing it up anyway. Let me know if deployment to conda will be required for your scenario. Closing for now.
